// console.log("Hi Joshua")
// console.log(Math.round(Math.random()*10))
// console.log(Math.floor(Math.random()*10))
console.log("   |   |")
console.log("   |   |")
console.log("   |   |")
console.log("-----------")
console.log("   |   |")
console.log("   |   |")
console.log("   |   |")
console.log("-----------")
console.log("   |   |")
console.log("   |   |")
console.log("   |   |")
